# Generated by Django 5.1.4 on 2025-01-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='feedimage',
            field=models.ImageField(upload_to='gallery_images/'),
        ),
    ]
